### ISSUE TITLE
Licensing of this project

### ISSUE THREAD

**Issue by jliebers** [picoxr/EyeTracking#1]
Dear Developers,

may I ask under which software license this repository is published? 

I find it very useful and would like to create a fork of it (i.e., making it a starting point for new projects as I find the gaze coordinate system with the green gaze point very useful). 🙂 

Thank you kindly in advance for your response.

Kind Regards,

Jonathan

**Comment by picoxr** [comment]
Hi Jonathan,

Our EyeTracking repo is for demo purpose and doesn't require license. You can use the code in your own applications.

**Comment by jliebers** [comment]
Thank you kindly for your response and permission. :)
